services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nefeshapps-pos-frontend
    ports:
      - "127.0.0.1:3002:3002"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
